- name: Create docker directory
  file:
      path: "{{ docker_destination }}/docker"
      state: directory

- name: Create deployment directory
  file:
      path: "{{ mediawiki_destination }}/mediawiki"
      state: directory

- name: Clone addshore mediawiki-dev
  git:
      recursive: no
      repo: "https://github.com/addshore/mediawiki-docker-dev.git"
      version: master
      dest: "{{ docker_destination }}/docker"

- name: Clone mediawiki
  git:
      recursive: no
      repo: "{{ mediawiki_src }}"
      version: master
      dest: "{{ mediawiki_destination }}/mediawiki"

- name: Clone skin(s)
  git:
      recursive: no
      repo: "{{ item.src }}"
      version: master
      dest: "{{ mediawiki_destination }}/mediawiki/skins/{{ item.name }}"
  with_items: "{{ skins }}"

- name: Clone extensions
  git:
      recursive: yes
      repo: "{{ item.src }}"
      version: master
      dest: "{{ mediawiki_destination }}/mediawiki/extensions/{{ item.name }}"
  with_items: "{{ extensions }}"

- name: Add composer dependencies
  script: ../files/addToComposer.py -a "{{ item.composer }}" -d "{{ mediawiki_destination }}/mediawiki"
  args:
      executable: python3
  with_items: "{{ extensions }}"
